#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi


# exec startxfce4
exec i3

# exec mate-session
# exec startlxqt
# exec startlxde
# exec gnome-session
# exec gnome-session --session=gnome-classic
# exec startkde
# exec cinnamon-session
