#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/*; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

if which polybar
then
    WM_CMD="i3"
else

    WM_CMD="i3 -c /tmp/i3_config"

    cat ~/.config/i3/config > /tmp/i3_config
    cat >> /tmp/i3_config <<EOL

bar {
        i3bar_command i3bar
        status_command i3status
        position bottom
        strip_workspace_numbers yes
        font pango:Roboto Mono 11
        colors {
            background #131313
            statusline #dcdccc
            separator  #3f3f3f
#                              border  backgr. text
            focused_workspace  #dcdccc #16a085 #131313
            active_workspace   #777777 #3f3f3f #dcdccc
            inactive_workspace #777777 #131313 #dcdccc
            binding_mode       #16a085 #2c2c2c #dcdccc
            urgent_workspace   #16a085 #dcdccc #dc322f
        }
}
EOL


fi


exec $WM_CMD

