#if [ -f ~/.zshrc ]; then
#    source ~/.zshrc
#fi

export PATH=$PATH":/snap/bin:/home/$USER/.local/bin"
export PATH=".:"$PATH
export TERMINAL='termite'
export DOTFILES_ROOT="/home/$USER/.dotfiles"

if which google-chrome-stable > /dev/null 2>&1
then
    export BROWSER=$(which google-chrome-stable)
elif which google-chrome > /dev/null 2>&1
then
    export BROWSER=$(which google-chrome)
elif which firefox > /dev/null 2>&1
then
    export BROWSER=$(which firefox)
fi

#DEFAULT_INTERFACE=$(ip route | grep -e '^default' | awk '{print $5}' | head -n1)
#ETH_INTERFACE=$(cat /proc/net/dev | grep -e '^en' | cut -d: -f1 | head -n1)
#WLAN_INTERFACE=$(cat /proc/net/dev | grep -e '^wl' | cut -d: -f1 | head -n1)
#export DEFAULT_INTERFACE
#export ETH_INTERFACE
#export WLAN_INTERFACE


[[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] && exec startx
#[[ -z $DISPLAY && $XDG_VTNR -le 3 ]] && exec startx
