# .zprofile
# [Read at login]
# It is for commands and variables which should be set once or which don't need to be updated frequently: is basically the same as .zlogin except that it's sourced before .zshrc while .zlogin is sourced after .zshrc

export DOTFILES_ROOT="/home/$USER/.dotfiles"
export MY_SHELL="/home/$USER/.my_shell"

if [ -z $AUTOSTART_FILE ]
then
    export AUTOSTART_FILE="/home/$USER/.local/bin/autostart.sh"
fi

if which google-chrome-stable > /dev/null 2>&1
then
    export BROWSER=$(which google-chrome-stable)
elif which google-chrome > /dev/null 2>&1
then
    export BROWSER=$(which google-chrome)
elif which firefox > /dev/null 2>&1
then
    export BROWSER=$(which firefox)
fi


if which alacritty > /dev/null 2>&1
then
    export TERMINAL=$(which alacritty)
elif which kitty > /dev/null 2>&1
then
    export TERMINAL=$(which kitty)
elif which termite > /dev/null 2>&1
then
    export TERMINAL=$(which termite)
elif which xfce4-terminal > /dev/null 2>&1
then
    export TERMINAL=$(which xfce4-terminal)
elif which uxterm > /dev/null 2>&1
then
    export TERMINAL=$(which uxterm)
fi


#DEFAULT_INTERFACE=$(ip route | grep -e '^default' | awk '{print $5}' | head -n1)
#ETH_INTERFACE=$(cat /proc/net/dev | grep -e '^en' | cut -d: -f1 | head -n1)
#WLAN_INTERFACE=$(cat /proc/net/dev | grep -e '^wl' | cut -d: -f1 | head -n1)
#export DEFAULT_INTERFACE
#export ETH_INTERFACE
#export WLAN_INTERFACE


[[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] && exec startx
#[[ -z $DISPLAY && $XDG_VTNR -eq 5 ]] && exec startx
#[[ -z $DISPLAY && $XDG_VTNR -le 3 ]] && exec startx
