# .zshenv
# [Read every time]
# This file is always sourced, so it should set environment variables which need to be updated frequently

export TERM='xterm-256color'
#export TERMINAL='termite'
export EDITOR='vim'
export VISUAL='vim'
#export LANG=it_IT.UTF-8
export LANG=en_US.UTF-8

export MY_ZSH="/home/$USER/.my_zsh"
export DOTFILES_ROOT="/home/$USER/.dotfiles"

# PATH
export PATH="/home/$USER/.local/bin:/snap/bin:"$PATH
export PATH="$DOTFILES_ROOT/custom:"$PATH
export PATH=".:"$PATH
