[bell]
animation = "EaseOutExpo"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.normal]
black = "#000000"
blue = "#1e90ff"
cyan = "#00cccc"
green = "#98fb98"
magenta = "#9966ff"
red = "#dc322f"
white = "#fdf6e3"
yellow = "#ffa500"

[colors.primary]
background = "#131313"
foreground = "#dcdccc"

[colors.search.focused_match]
background = "#ffa500"
foreground = "#fdf6e3"

[colors.search.matches]
background = "#dc322f"
foreground = "#fdf6e3"

[colors.selection]
background = "CellForeground"
text = "CellBackground"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"

[cursor]
blink_interval = 500
thickness = 0.1
unfocused_hollow = true
vi_mode_style = "None"

[cursor.style]
blinking = "On"
shape = "Block"

[font]
size = 11.0

[font.normal]
family = "monospace"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Alt"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[selection]
save_to_clipboard = false

[window]
decorations = "full"

[window.padding]
x = 5
y = 2
